### ISSUE TITLE
Add support for Health Snapshot and Heart Rate Variability for Garmin

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-PushEndpoint#42]
Select high end Garmin watches support these features now.

*Health snapshot*: 
The Garmin Health Snapshot is a collection of key health-related insights recorded during a two-minute session on a compatible device. Heart rate (HR), heart rate variability (HRV), Pulse Ox, respiration, and stress are the metrics included this summary, which collectively provide you a glimpse of your overall cardiovascular status. More information about Health Snapshot can be found at https://support.garmin.com/en-US/?faq=PB1duL5p6V64IQwhNvcRK9.

*Heart Rate Variability*: 
Heart rate variability (HRV) refers to beat-to-beat variations in heart rate and is data collected during the overnight sleep window for select devices. To gain a deeper understanding of your overall health, recovery and training performance through heart rate variability while you sleep, please visit https://discover.garmin.com/en-US/performance-data/running/#heart-rate-variability.
https://www.garmin.com/en-US/garmin-technology/running-science/physiological-measurements/hrv/

For specification and implementation details look at Health API documentation from Garmin Developer Portal

**Comment by afolarin** [comment]
for HRV this is only available via the Snapshot and the overnight sleep window. I guess maybe ambulatory HRV is difficult due to motion pulse wave artefacts.

**Comment by yatharthranjan** [comment]
Completed via #53
