### ISSUE TITLE
Add support for authenticating multiple users in a single payload

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/RADAR-PushEndpoint#9]
- Currently, the auth validator only checks the first data node in the payload sent by Garmin to the endpoint. There may be cases where a single payload can have data from multiple users (and thus multiple userAccessTokens), so we should support this
- Although there is only a single userAccessToken in the header 
- Sample file attached

[garmin.txt](https://github.com/RADAR-base/RADAR-PushEndpoint/files/5880362/garmin.txt)

**Comment by yatharthranjan** [comment]
Good spot, i think this is quite severe, since we only add the user once at the verifcation step, that means data could end up under wrong users. Moreover, since our whole structure is based around one user per request, it will need some refactoring and rethinking.

**Comment by yatharthranjan** [comment]
This is a little deeper than I first thought. There are bigger questions here-

- Do we remove the data for the user which is not authorized and return a 200 response? In this case, Garmin API would think all the data was successful and never send that data again.
- Do we send a 401 response when even a single node in the payload has a user which is unauthorized. In this case, garmin would resend the data later, but it would mean missing on data from the valid users in the payload (unless all the users are authorized).

Any suggestions would be appreciated @afolarin, @blootsvoets, @mpgxvii

**Comment by yatharthranjan** [comment]
IMO, the first method is better since less chance for missing data for authorised users and if an unauthorised user is later authorised we can always request the data from the developer portal (like backfill).

**Comment by mpgxvii** [comment]
I was just wondering would there be a case where a user is authorized in the Garmin app but not in our rest sources user repository (aside from using the test env)? Maybe this was all because of the inconsistent states due to us testing the same Garmin app in different envs? Also maybe if we receive someone who is not authorized, we can send a 401 response and then deregister the user?

**Comment by blootsvoets** [comment]
How about processing the data of users that are authorised, but still sending 401 if at least one of them is not authorised? The worst case is that this will generate a lot of duplicate records though.

**Comment by yatharthranjan** [comment]
>I was just wondering would there be a case where a user is authorized in the Garmin app but not in our rest sources user repository (aside from using the test env)? Maybe this was all because of the inconsistent states due to us testing the same Garmin app in different envs?

Yes i think this will be a very rare case but would be good to handle in any case. 

>On the other hand, maybe if we receive someone who is not authorized, we can go with solution 2, send a 401 response and then deregister the user right after?

Yes i think the deregistering of the user is a very good idea.


>How about processing the data of users that are authorised, but still sending 401 if at least one of them is not authorised? The worst case is that this will generate a lot of duplicate records though.

Yes, it think combining both of your suggestions would be good-

- Process the data of the users that are authorised.
- Send deregister to the garmin endpoint for the user that are unauthorised.
- send 401 response.

This will also mean minimal duplication of data will happen. 
What do you think?

**Comment by mpgxvii** [comment]
Yup good idea 👍
